"""add_slug_to_item

Revision ID: 07fbd3fa28bf
Revises: 164f205cf8ee
Create Date: 2025-01-20 12:59:11.530708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07fbd3fa28bf'
down_revision: Union[str, None] = '164f205cf8ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('slug', sa.String(), nullable=True))
    op.create_index(op.f('ix_items_slug'), 'items', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_items_slug'), table_name='items')
    op.drop_column('items', 'slug')
    # ### end Alembic commands ###
