"""item_name_not_unique

Revision ID: e7e9e80dd577
Revises: 07fbd3fa28bf
Create Date: 2025-01-20 13:32:51.434874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7e9e80dd577'
down_revision: Union[str, None] = '07fbd3fa28bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_items_name', table_name='items')
    op.create_index(op.f('ix_items_name'), 'items', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_items_name'), table_name='items')
    op.create_index('ix_items_name', 'items', ['name'], unique=True)
    # ### end Alembic commands ###
